#include "build_tool_test_support.h"
#include <algorithm>
#include <iostream>
using namespace build_test;
namespace {
int count(const fs::path& path){if(!fs::exists(path))return 0;auto text=read(path);return static_cast<int>(std::count(text.begin(),text.end(),'\n'));}
void process_cases(const fs::path& repo){
    auto root=temporary("retry-process");copy(repo,root,{"scripts/build_wait_tasks.py","scripts/powershell_runtime.py","scripts/build_test_retry.py","scripts/test_output.ps1","scripts/build_inputs.ps1","scripts/build_batch_tests.ps1","scripts/build_runtime.ps1","tools/build-dashboard/server.py"});fs::create_directories(root/L"bin");fs::copy_file(standin(),root/L"bin/ctest.exe");write(root/L".gitignore",".build/\nbin/\n");write(root/L"source.cpp","source identity");
    write(root/L"scripts/test_manager.ps1",R"PS(param([string]$Mode,[string]$PlanBatch)
$root=Split-Path $PSScriptRoot -Parent;$dir=Join-Path $root '.build/collaboration';$work=Join-Path $dir ($PlanBatch+'.retry');$control=[IO.File]::ReadAllText((Join-Path $root '.build/control'));$full=$control.StartsWith('full-')
. (Join-Path $PSScriptRoot 'test_output.ps1');$check=New-OutputIsolationCheck
if($control -eq 'full-failed-check'){$check.status='failed';$check.exitCode=7;$check.error='original output checkpoint failure';$check.startedUtc='2026-01-01T00:00:00Z';$check.completedUtc='2026-01-01T00:00:01Z'}
[IO.File]::AppendAllText((Join-Path $root '.build/initial.count'),"once`n");$report=Join-Path $work 'initial.xml'
[IO.File]::WriteAllText($report,('<testsuite><testcase name="build_dashboard">'+$(if($control -eq 'full-failed-check'){''}else{'<failure>structured resource fixture</failure>'})+'</testcase><testcase name="Deterministic"/></testsuite>'))
$coverage=@{schemaVersion=1;batchId=$PlanBatch;mode=$(if($full){'full'}else{'selected'});status='failed';selected=@('build_dashboard','Deterministic');completed=@();tasks=@(@{participant='fixture';requested=@('build_dashboard','Deterministic');status='failed';requiresOutputIsolation=$full});report=$report;error='initial fixture failed'}
if($full -and $control -ne 'full-legacy'){$coverage.postChecks=@{outputIsolation=$check}}
$coverage|ConvertTo-Json -Depth 10|Set-Content (Join-Path $dir ($PlanBatch+'.coverage.json')) -Encoding UTF8
if($control -ne 'assertion'){
 $signal=@{test='build_dashboard';runToken=$env:SNOWDESKTOP_RETRY_RUN_TOKEN;exitCode=75;failureClass='isolated-port-race';cleanupComplete=$true;sideEffects='none';reason='controlled ephemeral port failure'}
 if($control -eq 'bad-token'){$signal.runToken='invalid'};if($control -eq 'dirty'){$signal.cleanupComplete=$false};if($control -eq 'side-effect'){$signal.sideEffects='unknown'}
 $signal|ConvertTo-Json|Set-Content (Join-Path $env:SNOWDESKTOP_RETRY_SIGNAL_DIR 'build_dashboard.json') -Encoding UTF8
}
if($control -eq 'pre-change'){[IO.File]::WriteAllText((Join-Path $root 'source.cpp'),'changed before retry')}
exit 1
)PS",true);init_git(root);Bridge bridge(repo,root);auto state=root/L".build/collaboration";fs::create_directories(state);Env env{{L"PATH",(root/L"bin").wstring()+L";"+environment(L"PATH")}};
    struct Case{const char* mode;int code,attempts;};int index=0;
    for(const Case item:std::vector<Case>{{"once",0,1},{"always",1,2},{"assertion",1,0},{"change",5,1},{"full-once",0,1},{"full-bad-output",1,1},{"full-failed-check",7,0},{"full-legacy",0,1},{"unreviewed",1,0},{"bad-token",1,0},{"dirty",1,0},{"side-effect",1,0},{"pre-change",5,0}}){
        std::string mode=item.mode,batch(32,"123456789abcde"[index++]);bool full=mode.starts_with("full-");write(state/wide(batch+".plan.json"),Json::object({{"schemaVersion",1},{"batchId",batch},{"configuration","Release"},{"mode",full?"full":"selected"},{"buildRequired",false}}).dump());write(root/L".build/control",mode);write(root/L".build/Release/tests/SnowDesktopFixtureTests.exe","isolated fixture");fs::create_directories(root/L".build/Release/SnowDesktop.Runtime");fs::remove(root/L".build/Release/escaped.dll");if(mode=="full-bad-output")write(root/L".build/Release/escaped.dll","escaped output");write(root/L"source.cpp","initial "+mode);auto before=count(root/L".build/ctest.count");auto result=bridge.invoke(root/L"scripts/build_batch_tests.ps1",{"-Batch",batch},env,45);require(result.code==item.code,mode+result.out+result.err);require(count(root/L".build/ctest.count")-before==item.attempts,"Unexpected retry count "+mode);auto ledger=Json::parse(read(state/wide(batch+".retry.json"))),coverage=Json::parse(read(state/wide(batch+".coverage.json")));require(ledger.at("selected").items.size()==2&&ledger.at("initialExitCode").integer()==1&&ledger.at("tests").at("Deterministic").at("attempts").items.size()==1,"Retry changed denominator/repeated passed test");
        if(mode=="once")require(coverage.at("status").str()=="passed-after-retry"&&coverage.at("flaky").dump()==Json::array({"build_dashboard"}).dump()&&coverage.at("tasks").items[0].at("status").str()=="passed-after-retry","Flaky success lost attribution");if(mode=="always")require(ledger.at("tests").at("build_dashboard").at("failureCount").integer()==3&&ledger.at("tests").at("build_dashboard").at("status").str()=="exhausted-failed","Retry exhaustion was not finite");if(mode=="change"||mode=="pre-change")require(ledger.at("status").str()=="invalidated","Changed input not invalidated");
        if(full){auto check=coverage.at("postChecks").at("outputIsolation");require(check.at("status").str()==(item.code?"failed":"passed")&&ledger.at("postChecks").dump()==coverage.at("postChecks").dump(),"Full checkpoint lost/evidence differs");auto evidence=state/wide(batch+".retry/output-isolation.json");if(mode=="full-failed-check")require(!fs::exists(evidence)&&check.at("exitCode").integer()==7&&check.at("error").str()=="original output checkpoint failure","Original checkpoint was overwritten");else require(fs::exists(evidence)&&!check.at("startedUtc").str().empty()&&!check.at("completedUtc").str().empty(),"Full output checkpoint was not executed");require(coverage.at("completed").items.size()==2,"Full retry dropped completed tests");}
        auto initial=read(root/L".build/initial.count"),firstXml=read(state/wide(batch+".retry/initial.xml"));auto replay=run({production_python().wstring(),(root/L"scripts/build_test_retry.py").wstring(),L"--root",root.wstring(),L"--batch",wide(batch)},root,12,env);require(replay.code==item.code&&initial==read(root/L".build/initial.count")&&firstXml==read(state/wide(batch+".retry/initial.xml")),"Completed attempt replayed/first failure overwritten");std::cout<<"PASS retry "<<mode<<"\n";
    }
    std::string batch(32,'f');auto work=state/wide(batch+".retry");fs::create_directory(work);Child crashed({standin().wstring(),L"--crash-retry",L"--folder",work.wstring(),L"--batch",wide(batch)},root);require(crashed.wait().code==19,"Crash stand-in did not retain completed side effect");auto status=run({production_python().wstring(),(root/L"scripts/build_test_retry.py").wstring(),L"--root",root.wstring(),L"--batch",wide(batch),L"--status"},root);require(status.code==0&&Json::parse(status.out).at("status").str()=="interrupted","Exited runner with retained process handle appeared alive");auto replay=run({production_python().wstring(),(root/L"scripts/build_test_retry.py").wstring(),L"--root",root.wstring(),L"--batch",wide(batch)},root);require(replay.code==4&&read(work/L"side-effect.count")=="once"&&Json::parse(read(work/L"build_dashboard.attempt2.json")).at("status").str()=="passed","Crash replayed completed side effect");
}
void real_selection(const fs::path& repo){
    auto root=temporary("real-ctest-selection");copy(repo,root,{"scripts/build_job.cs","scripts/build_entry.ps1","scripts/test_manager.ps1","scripts/test_output.ps1","scripts/build_protocol.ps1"});
    auto probePath=utf8(standin().generic_wstring());write(root/L"CMakeLists.txt","cmake_minimum_required(VERSION 3.20)\nproject(RealSelection NONE)\nenable_testing()\nforeach(name Alpha Beta Gamma)\nadd_test(NAME ${name} COMMAND \""+probePath+"\" --selected-probe ${name})\nset_tests_properties(${name} PROPERTIES LABELS core TIMEOUT 10)\nendforeach()\n");
    write(root/L"CMakePresets.json",R"JSON({"version":3,"configurePresets":[{"name":"tests","binaryDir":"${sourceDir}/.build/ctest"}],"testPresets":[{"name":"all-tests","configurePreset":"tests","configuration":"Release","output":{"outputOnFailure":true}}]})JSON");Bridge bridge(repo,root);auto state=root/L".build/collaboration";auto plan=[&](const std::string& batch){auto requirement=Json::object({{"tests",Json::array({"Alpha","Beta"})},{"suites",Json::array({"selected"})},{"requiredFull",false},{"reason","real CTest literal selection"}});write(state/wide(batch+".plan.json"),Json::object({{"schemaVersion",1},{"batchId",batch},{"configuration","Release"},{"mode","selected"},{"suites",Json::array({"selected"})},{"tests",Json::array({"Alpha","Beta"})},{"tasks",Json::array({Json::object({{"participant","real-ctest"},{"requirement",requirement}})})}}).dump());};
    auto configured=run({L"cmake",L"--preset",L"tests"},root);require(configured.code==0,configured.out+configured.err);std::string batch(32,'1');plan(batch);auto result=bridge.invoke(root/L"scripts/test_manager.ps1",{"-Mode","plan","-PlanBatch",batch});require(result.code==0,result.out+result.err);auto coverage=Json::parse(read(state/wide(batch+".coverage.json")));require(coverage.at("selected").dump()==Json::array({"Alpha","Beta"}).dump()&&coverage.at("completed").items.size()==2&&read(root/L".build/ctest/executed.txt")=="Alpha\nBeta\n","Real CTest did not execute exact requested set");auto before=read(root/L".build/ctest/executed.txt");for(const auto& regex:{"^Missing$","^(?:Alpha|Beta)$"}){result=bridge.invoke(root/L"scripts/test_manager.ps1",{"-Mode","name","-Filter",regex});require(result.code!=0&&read(root/L".build/ctest/executed.txt")==before,"Zero/invalid CTest regex ran a test");}write(root/L".build/ctest/fail-beta","31");batch=std::string(32,'2');plan(batch);result=bridge.invoke(root/L"scripts/test_manager.ps1",{"-Mode","plan","-PlanBatch",batch});require(result.code!=0,result.out+result.err);coverage=Json::parse(read(state/wide(batch+".coverage.json")));require(coverage.at("completed").items.size()==2&&coverage.at("status").str()=="failed"&&coverage.at("tasks").items[0].at("failed").dump()==Json::array({"Beta"}).dump()&&read(root/L".build/ctest/executed.txt")=="Alpha\nBeta\nAlpha\nBeta\n","Real deterministic failure lost denominator/attribution");
}
void repairs(const fs::path& repo){
    Coordinator c(repo,"retry-repair");auto parent=c.begin("a").at("batchId").str();c.begin("b");write(c.root/L"fail-build","11");auto first=c.start(c.bound("finish","a",parent));auto failed=c.finish("b",parent,0,11);require(first->wait(30).code==11&&failed.at("outcome").str()=="failed"&&c.calls()==1,"Compiler failure ran tests");auto saved=read(c.stateRoot/wide(parent+".json"));c.gate("fail-build",false);auto repair=c.bound("repair","a",parent);repair.insert(repair.end(),{"-Reason","repair fixture compiler failure"});auto one=c.start(repair);repair[1]="b";auto two=c.start(repair);auto oneResult=one->wait(),twoResult=two->wait();require(oneResult.code==0&&twoResult.code==0,oneResult.err+twoResult.err);auto a=Json::parse(oneResult.out),b=Json::parse(twoResult.out);auto child=a.at("batchId").str();require(child==b.at("batchId").str()&&child!=parent&&a.at("attempt").integer()==2,"Concurrent repair created multiple children");c.call({"repair-abandon","-Batch",parent,"-Reason","active repair"},2);require(c.state().at("current").at("participants").items[0].at("testPlan").has("originalRequirement"),"Repair dropped original requirements");c.ready("a",child,0,2);fs::remove(c.stateRoot/wide(parent+".repair.json"));repair[1]="a";auto reconciled=c.call(repair);require(reconciled.at("batchId").str()==child&&reconciled.at("editRevision").integer()==a.at("editRevision").integer(),"Repair publication gap did not reconcile existing child");int rev=a.at("editRevision").integer();auto claim=c.bound("claim","a",child,rev);claim.insert(claim.end(),{"-Files","src/a.txt"});c.call(claim);write(c.root/L"src/a.txt","fixed input\n");c.ready("a",child,rev);c.ready("b",child,b.at("editRevision").integer());until([&]{return fs::exists(c.stateRoot/wide(child+".json"));},40);auto final=c.result(child);require(final.at("outcome").str()=="passed"&&final.at("repairOf").str()==parent&&final.at("logicalBatchId").str()==parent&&final.at("attempt").integer()==2&&saved==read(c.stateRoot/wide(parent+".json"))&&c.calls()==3,"Repair repeated pipeline/overwrote parent");c.call(repair,2);auto independent=c.begin("independent").at("batchId").str();c.call({"recover","independent","-Batch",independent,"-ConfirmStopped","-Reason","fixture stopped"});c.call({"repair-abandon","-Batch",parent,"-Reason","no further old-parent repair"});c.call(repair,2);require(saved==read(c.stateRoot/wide(parent+".json")),"Abandon erased original failure");
    parent=c.begin("a").at("batchId").str();c.begin("b");write(c.root/L"fail-build","11");c.plan("b",parent,0,"selected","ManualPreview");first=c.start(c.bound("finish","b",parent));c.finish("a",parent,0,11);require(first->wait().code==11,"Carried peer did not receive failure");saved=read(c.stateRoot/wide(parent+".json"));c.gate("fail-build",false);repair=c.bound("repair","a",parent);repair.insert(repair.end(),{"-Reason","solo repairer preserves peer"});a=c.call(repair);child=a.at("batchId").str();rev=a.at("editRevision").integer();claim=c.bound("claim","a",child,rev);claim.insert(claim.end(),{"-Files","src/a.txt"});c.call(claim,2);claim.push_back("-AdoptExistingChanges");c.call(claim);write(c.root/L"src/a.txt","second fixed input\n");c.ready("a",child,rev);until([&]{return fs::exists(c.stateRoot/wide(child+".json"));},40);final=c.result(child);require(final.at("outcome").str()=="passed"&&final.at("testingPlan").at("mode").str()=="full"&&final.at("participants").items.size()==2,"Solo repair did not carry/escalate prior requirements");bool manual=false;for(const auto& test:final.at("testingPlan").at("tests").items)if(test.str()=="ManualPreview")manual=true;require(manual&&saved==read(c.stateRoot/wide(parent+".json"))&&c.calls()==6,"Full repair lost explicit manual/immutable failure");for(const auto& task:final.at("participants").items)require(task.at("check").at("status").str()=="passed","Carried peer check not repeated");
}
void run_tests(const fs::path& repo){process_cases(repo);real_selection(repo);repairs(repo);}
}
int main(int argc,char** argv){return test_main(argc,argv,run_tests);}
