#include "build_tool_test_support.h"
#include <iostream>
using namespace build_test;
namespace {
Json complete(Child& child,int code=0){auto result=child.wait(40);require(result.code==code,result.out+result.err);return result.out.empty()?Json{}:Json::parse(result.out);}
void equal(const Json& a,const Json& b){require(a.dump()==b.dump(),"Waiters did not receive identical persisted results");}
void run_tests(const fs::path& repo){
    Coordinator c(repo,"collaboration");auto initial=c.call({"status"});require(initial.at("current").kind==Json::Kind::Null&&!fs::exists(c.stateRoot/L"state.json"),"status registered a batch");
    auto bid=c.begin("a").at("batchId").str();require(c.begin("b").at("batchId").str()==bid&&c.begin("a").at("batchId").str()==bid,"Overlapping/repeated begin split batch");
    auto scoped=c.plan("a",bid,0,"selected","Alpha","module","src/winui/presenter.cpp,src/core/desktop.cpp,scripts/build_protocol.ps1");require(!scoped.at("testPlan").at("requiredFull").boolean,"Module paths silently escalated coverage");auto empty=c.bound("plan","a",bid);empty.insert(empty.end(),{"-Scope","module","-Suites","selected"});c.call(empty,2);require(c.state().at("current").at("participants").items[0].at("testPlan").at("tests").dump()==Json::array({"Alpha"}).dump(),"Invalid plan replaced valid plan");
    for(const auto& risk:{"public","infrastructure","unknown"})require(c.plan("a",bid,0,"selected","Alpha",risk).at("testPlan").at("requiredFull").boolean,"High-risk plan omitted full coverage");c.plan("a",bid,0,"full","","unknown");c.finish("a",std::string(32,'0'),0,2);
    c.gate("hold-build");c.gate("hold-test");auto first=c.start(c.bound("finish","a",bid));until([&]{return c.state().at("current").at("participants").items[0].at("state").str()=="finished";});require(first->running()&&c.calls()==0,"First finisher built while peer edits");auto timeout=c.bound("finish","a",bid);timeout.insert(timeout.end(),{"-WaitSeconds","1"});c.call(timeout,2);require(c.state().at("current").at("participants").items.size()==2,"Timeout cleared peer registration");auto duplicate=c.start(c.bound("finish","a",bid));until([&]{return duplicate->err().find("Waiting")!=std::string::npos;});auto registration=c.state().at("current").at("participants").items[0].at("registeredUtc").str();auto reopened=c.begin("a");require(reopened.at("editRevision").integer()==1&&registration==c.state().at("current").at("participants").items[0].at("registeredUtc").str(),"Reopen changed membership/registration identity");complete(*first,2);complete(*duplicate,2);require(c.calls()==0&&c.begin("a").at("editRevision").integer()==1,"Superseded finish finalized reopened editor");c.plan("a",bid,1,"full","","unknown");auto args=c.bound("finish","a",bid,1);args.push_back("-ReloadShell");first=c.start(args);until([&]{return c.state().at("current").at("participants").items[0].at("state").str()=="finished";});require(c.calls()==0&&!fs::exists(c.root/L"preflight-arguments.txt"),"Reload request caused early process action");duplicate=c.start(c.bound("finish","a",bid,1));auto last=c.start(c.bound("finish","b",bid));until([&]{return fs::exists(c.root/L"build-started");});require(c.calls()==1&&read(c.root/L"preflight-arguments.txt")=="--reload-shell"&&read(c.root/L"build-arguments.txt").empty(),"Outer owner reload/single-build boundary broken");auto pending=c.start({"begin","c"});c.call({"begin","d","-WaitSeconds","1"},2);require(pending->running()&&c.state().at("current").at("participants").items.size()==2,"New begin entered frozen batch");c.gate("hold-build",false);until([&]{return fs::exists(c.root/L"test-started");});require(pending->running()&&c.calls()==2,"New editor entered during testing");c.gate("hold-test",false);auto resultA=complete(*first);equal(resultA,complete(*last));equal(resultA,complete(*duplicate));equal(resultA,c.finish("a",bid,1));require(resultA.at("inputCheck").str()=="stable"&&resultA.at("inputStart").at("digest").str()==resultA.at("inputEnd").at("digest").str(),"Result did not bind stable input identity");auto next=complete(*pending).at("batchId").str();require(next!=bid,"Queued begin reused frozen batch");equal(resultA,c.call({"status","-Batch",bid}));require(c.state().at("current").at("participants").items.size()==1,"Historical read disturbed next registration");c.finish("c",next);require(c.calls()==4&&read(c.root/L"build-arguments.txt").empty(),"Next batch inherited reload/pipeline");
    auto race=c.begin("race-a").at("batchId").str();c.begin("race-b");first=c.start(c.bound("finish","race-a",race));last=c.start(c.bound("finish","race-b",race));equal(complete(*first),complete(*last));require(c.calls()==6,"Simultaneous last finishes repeated pipeline");
    for(const std::string phase:{"build","test"}){auto before=c.calls();write(c.root/("fail-"+phase),"7");auto task="failure-"+phase;auto failedId=c.begin(task).at("batchId").str();auto failure=c.finish(task,failedId,0,7);require(failure.at("outcome").str()=="failed"&&failure.at("error").str().find("code 7")!=std::string::npos&&read(wide(failure.at("logPath").str())).find("controlled "+phase+" failure")!=std::string::npos,"Failure receipt/log lost original code");equal(failure,c.finish(task,failedId,0,7));require(c.calls()-before==(phase=="build"?1:2),"Failure repeated/skipped wrong pipeline step");c.gate("fail-"+phase,false);task="after-"+phase;c.finish(task,c.begin(task).at("batchId").str());}
    auto stale=c.begin("stale").at("batchId").str();c.begin("live");auto state=c.state();state["current"]["participants"].items[0]["registeredUtc"]="2000-01-01T00:00:00Z";atomic(c.stateRoot/L"state.json",state.dump());auto before=c.calls();last=c.start(c.bound("finish","live",stale));until([&]{return c.state().at("current").at("participants").items[1].at("state").str()=="finished";});require(c.calls()==before,"Registration age bypassed barrier");c.call({"recover","stale","-Batch",stale,"-Reason","inspected"},2);c.call({"recover","live","-Batch",stale,"-ConfirmStopped","-Reason","inspected"},2);c.call({"recover","stale","-Batch",stale,"-ConfirmStopped","-Reason","inspected"});auto staleResult=complete(*last);require(staleResult.at("participants").items[0].at("state").str()=="withdrawn"&&staleResult.at("participants").items[1].at("state").str()=="finished","Targeted withdrawal lost live registration");auto cancelled=c.begin("abandoned").at("batchId").str();c.call({"recover","abandoned","-Batch",cancelled,"-ConfirmStopped","-Reason","inspected"});require(c.call({"status","-Batch",cancelled}).at("outcome").str()=="cancelled","All-withdrawn batch became success");
    c.gate("build-started",false);c.gate("hold-build");auto crash=c.begin("crash").at("batchId").str();auto crashed=c.start(c.bound("finish","crash",crash));until([&]{return fs::exists(c.root/L"build-started");});auto ownedChild=Json::parse(read(c.root/L"child.json"));before=c.calls();c.call({"recover","-Batch",crash,"-ConfirmStopped","-Reason","inspected"},2);crashed->stop();until([&]{return !owner_alive(ownedChild);},5);require(c.call({"status"}).at("current").at("ownerState").str()=="exited","Orphan owner not identified");c.call({"begin","blocked","-WaitSeconds","1"},2);require(c.calls()==before,"Orphan automatically rebuilt");c.gate("hold-build",false);c.call({"recover","-Batch",crash,"-ConfirmStopped","-Reason","inspected"});auto interrupted=c.finish("crash",crash,0,4);require(interrupted.at("outcome").str()=="interrupted"&&interrupted.at("error").str()=="inspected","Explicit interruption lost result");auto after=c.begin("after-crash").at("batchId").str();c.call({"recover","nobody","-Batch",crash,"-ConfirmStopped","-Reason","inspected"});require(c.state().at("current").at("id").str()==after,"Old recovery cleared next batch");c.finish("after-crash",after);
    state=c.state();state["current"]=Json::object({{"id",bid},{"phase","building"},{"participants",resultA.at("participants")},{"createdUtc",resultA.at("createdUtc")},{"buildStartedUtc",resultA.at("buildStartedUtc")},{"logPath",resultA.at("logPath")},{"owner",Json::object({{"pid",static_cast<double>(GetCurrentProcessId())},{"startTicks","0"}})}});atomic(c.stateRoot/L"state.json",state.dump());before=c.calls();c.call({"recover","-Batch",bid,"-ConfirmStopped","-Reason","published"});require(c.state().at("current").kind==Json::Kind::Null&&c.calls()==before,"Published-result recovery reran pipeline");
    before=c.calls();c.gate("preflight-unknown");auto guarded=c.begin("output-owner").at("batchId").str();first=c.start(c.bound("finish","output-owner",guarded));auto observed=[&](const std::string& status){auto current=c.state().at("current");return current.has("preflight")&&current.at("preflight").at("status").str()==status;};until([&]{return observed("unknown");});require(first->running()&&c.calls()==before,"Unknown output owner allowed build");c.gate("preflight-blocked");c.gate("preflight-unknown",false);until([&]{return observed("blocked");});require(first->running()&&c.calls()==before,"Blocked output owner allowed build");c.gate("preflight-blocked",false);require(complete(*first).at("outcome").str()=="passed"&&c.calls()==before+2,"Clear ownership did not resume one pipeline");
    c.gate("preflight-throw");auto preflightId=c.begin("preflight-failure").at("batchId").str();args=c.bound("finish","preflight-failure",preflightId);args.push_back("-ReloadShell");before=c.calls();auto failure=c.call(args,3);auto checkpoint=Json::parse(read(c.stateRoot/wide(preflightId+".preflight.json")));require(c.calls()==before&&checkpoint.at("exitCode").integer()==3&&checkpoint.at("error").str().find("controlled owner preflight exception")!=std::string::npos&&read(wide(failure.at("logPath").str())).find("controlled owner preflight exception")!=std::string::npos,"Pre-Job exception lost evidence or ran native child");c.gate("preflight-throw",false);
    for(const std::string change:{"content","addition","deletion","rename","configuration","local-configuration"}){
        if(change=="deletion")c.git({L"add",L"src/added.h"});c.gate("build-started",false);c.gate("hold-build");auto task="input-"+change;auto changed=c.begin(task).at("batchId").str();first=c.start(c.bound("finish",task,changed));until([&]{return fs::exists(c.root/L"build-started");});
        if(change=="content")write(c.root/L"src/fixture.cpp","modified source");if(change=="addition")write(c.root/L"src/added.h","new input");if(change=="deletion")fs::remove(c.root/L"src/added.h");if(change=="rename")fs::rename(c.root/L"src/fixture.cpp",c.root/L"src/renamed.cpp");if(change=="configuration")write(c.root/L"CMakePresets.json","{\"version\":6}");if(change=="local-configuration")write(c.root/L"CMakeUserPresets.json","{\"version\":6}");c.gate("hold-build",false);auto invalid=complete(*first,5);require(invalid.at("outcome").str()=="invalidated"&&invalid.at("pipelineExitCode").integer()==0&&invalid.at("inputStart").at("digest").str()!=invalid.at("inputEnd").at("digest").str(),"Input change did not invalidate success: "+change);equal(invalid,c.finish(task,changed,0,5));
    }
    c.finish("a",bid,1,2);auto newA=c.begin("a").at("batchId").str();c.finish("a",bid,1,2);require(c.state().at("current").at("id").str()==newA,"Old passed result finished new editor");auto fresh=c.finish("a",newA);require(fresh.at("inputCheck").str()=="stable"&&fresh.at("inputStart").at("digest").str()!=resultA.at("inputStart").at("digest").str(),"New result reused old input identity");equal(resultA,c.call({"status","-Batch",bid}));
    std::cout<<"PASS coordinator overlap, race, failure, crash, preflight and six input invalidations\n";
}
}
int main(int argc,char** argv){return test_main(argc,argv,run_tests);}
