#pragma once

#include "desktop_hover_types.h"

#include <cstdint>

namespace snowdesktop::desktop_hover_rules
{
inline constexpr std::uint32_t kActivationSettleMs = 150;

constexpr ReconcileMode ShellPopupCloseReconcileMode()
{
    // A Shell verb may return before its asynchronous confirmation dialog is
    // created. The menu's final cursor position therefore cannot prove that
    // the pointer has returned to the desktop interaction surface.
    return ReconcileMode::DeactivateOnly;
}

constexpr bool ShouldHoldHoverDuringNativeShellPopup(
    bool nativeShellPopupLayerActive)
{
    // TrackPopupMenuEx captures the pointer for a transient Shell-owned
    // window. Its WM_MOUSELEAVE does not mean that the pointer left the Dock's
    // logical content/backdrop pair, so keep one frame until the menu session
    // has unwound and the live cursor can be sampled again.
    return nativeShellPopupLayerActive;
}

constexpr bool ShouldRetainHoverAcrossMouseLeave(
    bool pointerOnContentWindow,
    bool pointerOnPairedBackdropWindow)
{
    return pointerOnContentWindow ||
        pointerOnPairedBackdropWindow;
}

constexpr bool ShouldClearRejectedDesktopHover(
    bool hoverPresent, bool pointerOnDockSurface, bool pointerInDockLayer)
{
    // A queued desktop move can arrive after the Dock's newer move. Reject
    // that stale message without clearing the hover owned by the Dock.
    return hoverPresent && !(pointerOnDockSurface && pointerInDockLayer);
}

template<typename RearmTracking>
bool RetainPairedSurfaceMouseLeave(
    bool pointerOnContentWindow,
    bool pointerOnPairedBackdropWindow,
    RearmTracking rearmTracking)
{
    if (!ShouldRetainHoverAcrossMouseLeave(
            pointerOnContentWindow, pointerOnPairedBackdropWindow))
        return false;
    // Only the content HWND owns this leave subscription. Retain a backdrop
    // handoff without replaying input, changing regions or scheduling a paint.
    if (pointerOnContentWindow)
        rearmTracking();
    return true;
}

constexpr bool ShouldResamplePassiveMouseMove(
    bool mouseDown,
    bool dragActive,
    bool widgetInteractionActive)
{
    return !mouseDown &&
        !dragActive &&
        !widgetInteractionActive;
}

constexpr bool CanCoalescePassiveMouseMoves(
    bool passiveHover, bool pointerButtonsDown,
    bool transportActive, bool captureActive)
{
    // Pressed widget input and OLE retain their own sample/release ordering.
    // Passive hover needs only the newest point in each consecutive segment.
    return passiveHover && !pointerButtonsDown &&
        !transportActive && !captureActive;
}

constexpr bool ShouldProbeMouseMoveQueue(
    bool nativeGesture, bool passiveHover, bool postedWorkPending)
{
    // User32 already merges physical mouse movement on retrieval. A second
    // PeekMessage can generate another move (and hit testing) instead of
    // finding an older sample. Explicitly posted work still needs compaction.
    return nativeGesture || (passiveHover && postedWorkPending);
}

constexpr bool ShouldPresentRetainedMouseLeave(
    bool passiveHover,
    bool pointerPositionChanged)
{
    // A retained leave can be generated by a backdrop-region update while the
    // physical pointer is stationary. Repainting that unchanged state would
    // recreate the content/backdrop move-leave feedback loop. A changed live
    // point, however, must be presented once because the content HWND may not
    // receive another move after the backdrop takes over hit testing.
    return passiveHover && pointerPositionChanged;
}

constexpr bool HasForegroundSettled(
    bool foregroundChangeKnown,
    std::uint32_t elapsedMs)
{
    return !foregroundChangeKnown ||
        elapsedMs >= kActivationSettleMs;
}

constexpr bool ShouldReconcileFromSurfaceSample(
    bool nativeShellPopupLayerActive,
    bool shellDialogOwnerAvailable,
    bool shellDialogOwnerEnabled)
{
    const bool nativeShellModalSessionActive =
        nativeShellPopupLayerActive ||
        (shellDialogOwnerAvailable && !shellDialogOwnerEnabled);
    return !nativeShellModalSessionActive;
}

template<typename Handle>
constexpr bool OwnsInteractionCapture(
    Handle captureWindow,
    Handle desktopWindow,
    Handle floatingDockWindow)
{
    return captureWindow != Handle{} &&
        (captureWindow == desktopWindow ||
            captureWindow == floatingDockWindow);
}

constexpr bool CanClearPassiveHover(
    bool ownsInteractionCapture,
    bool mouseDown,
    bool dragActive,
    bool widgetInteractionActive)
{
    return !ownsInteractionCapture &&
        !mouseDown &&
        !dragActive &&
        !widgetInteractionActive;
}

constexpr bool ShouldPresentSynchronously(
    bool hoverTargetChanged,
    bool continuousPointerSurface)
{
    return hoverTargetChanged ||
        continuousPointerSurface;
}

constexpr bool ShouldActivateFromSurfaceSample(
    bool pointerOnDesktopSurface,
    bool passiveHoverCleared,
    ReconcileMode mode,
    bool foregroundSettled)
{
    const bool activationAllowed =
        mode == ReconcileMode::AllowImmediateActivation ||
        (mode == ReconcileMode::AllowActivationAfterForegroundSettle &&
            foregroundSettled);
    return pointerOnDesktopSurface &&
        passiveHoverCleared &&
        activationAllowed;
}

constexpr bool ShouldRefreshActiveHoverFromSurfaceSample(
    bool pointerOnActiveHoverSurface,
    bool passiveHoverCleared,
    bool pointerPositionChanged,
    bool passiveHoverAllowed,
    ReconcileMode mode,
    bool foregroundSettled)
{
    const bool activationAllowed =
        mode == ReconcileMode::AllowImmediateActivation ||
        (mode == ReconcileMode::AllowActivationAfterForegroundSettle &&
            foregroundSettled);
    return pointerOnActiveHoverSurface &&
        !passiveHoverCleared &&
        pointerPositionChanged &&
        passiveHoverAllowed &&
        activationAllowed;
}

constexpr bool IsActiveHoverSampleSurface(
    bool pointerOnBaseDesktopSurface,
    bool pointerOnDockSurface, bool pointerInDockLayer)
{
    // A preview/popup bridge is not a passive-hover acquisition surface.
    // Dock content and its paired backdrop are, within their logical region.
    return pointerOnBaseDesktopSurface ||
        (pointerOnDockSurface && pointerInDockLayer);
}
}
