"""Generate an offline PUBLIC holiday snapshot; no observed/substitute dates.

Python 3.10+, pip install holidays==0.95 python-dateutil==2.9.0.post0 six==1.17.0
Run from any directory. Runtime has no Python/network dependency.
"""
import json
import re
from pathlib import Path
import holidays

ROOT = Path(__file__).resolve().parents[1]
REGIONS = ('CN', 'TW', 'HK', 'JP', 'KR', 'US', 'GB', 'DE', 'FR', 'ES', 'MX', 'BR',
           'TH', 'IL', 'IR', 'SA', 'IN')
LANGUAGES = ('en_US', 'zh_CN', 'zh_TW', 'ja', 'ko', 'de', 'fr', 'es', 'pt_BR')
FIRST, LAST = 2020, 2035

def main():
    if holidays.__version__ != '0.95':
        raise RuntimeError('Expected holidays 0.95')
    rows = []
    for region in REGIONS:
        base = holidays.country_holidays(region)
        languages = sorted(set(LANGUAGES) & set(base.supported_languages))
        languages = sorted(set(languages + [base.default_language or 'en_US']))
        for language in languages:
            dates = holidays.country_holidays(region, years=range(FIRST, LAST + 1),
                observed=False, language=language, categories=holidays.PUBLIC)
            # Some regions add transferred rest days independently of observed=False.
            # Match the provider's translated substitution template, not holiday dates.
            substitution = getattr(dates, 'substituted_label', None)
            substitution_pattern = (re.compile('^' + re.escape(dates.tr(substitution)).replace('%s', '.*') + '$')
                                    if substitution else None)
            for date, names in sorted(dates.items()):
                # Keep the library's real multi-day holidays; never collapse by name.
                for name in dates.get_list(date):
                    if substitution_pattern and substitution_pattern.fullmatch(name):
                        continue
                    rows.append((region, language, date.isoformat(), name))
    output = ['// Generated by scripts/generate_calendar_holidays.py; holidays 0.95 (MIT).',
              '// PUBLIC only, observed=False, 2020-2035. Future entries are rule-based.',
              'static constexpr HolidayEntry kHolidayEntries[] = {']
    output += ['    {' + ', '.join(json.dumps(s, ensure_ascii=False) for s in row) + '},'
               for row in sorted(rows)]
    output += ['};', '']
    (ROOT / 'src/calendar_holidays.inc').write_text('\n'.join(output), encoding='utf-8')
    print(f'Generated {len(rows)} holiday records')

if __name__ == '__main__':
    main()
