"""Embed the pinned WinUI noise PNG without a runtime file dependency."""

import argparse
import hashlib
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    source = root / "third_party/microsoft-ui-xaml/NoiseAsset_256X256_PNG.png"
    target = root / "src/acrylic_noise_asset.h"
    data = source.read_bytes()
    expected_hash = "4f2aa94a2e345a32dae689176b86c644bef87081ff9daef8c77417731862031b"
    if hashlib.sha256(data).hexdigest() != expected_hash:
        raise SystemExit("The WinUI noise PNG does not match the pinned upstream asset")
    rows = ["    " + ", ".join(f"0x{value:02x}" for value in data[i:i + 16]) + ","
            for i in range(0, len(data), 16)]
    text = "\n".join([
        "// Generated by scripts/generate_acrylic_noise_asset.py; do not edit.",
        "// Copyright (c) Microsoft Corporation. All rights reserved.",
        "// MIT license: third_party/microsoft-ui-xaml/LICENSE.",
        "// Upstream commit: 7b68d3e0b771a57d80098799406234efee479517.",
        "#pragma once", "#include <array>", "#include <cstdint>", "",
        "namespace snowdesktop::acrylic_noise_asset", "{",
        f"inline constexpr std::array<std::uint8_t, {len(data)}> Png{{{{",
        *rows, "}};", "}", "",
    ])
    if args.check:
        if not target.is_file() or target.read_text(encoding="utf-8") != text:
            raise SystemExit("The embedded WinUI noise asset is stale; regenerate it")
        print("Pinned WinUI noise asset and embedded header match")
    else:
        with target.open("w", encoding="utf-8", newline="\n") as output:
            output.write(text)
        print(f"Embedded {len(data)} bytes into {target}")


if __name__ == "__main__":
    main()
