/**
 * @file resource.h
 * @brief 资源标识符定义
 * @details 定义应用程序图标、字体等资源的ID
 */
#pragma once

#define IDI_APPICON 1
#define IDI_APPICON_SMALL 2
#define IDR_FA_FONT 3
#define IDR_FLUENT_REGULAR_FONT 4

// Fictional Fluent-style application icons used by Demo Mode.
// Keep this range contiguous; rendering indexes into it by visual identity.
#define IDR_DEMO_ICON_PROJECTS 100
#define IDR_DEMO_ICON_DESIGN 101
#define IDR_DEMO_ICON_FOCUS 102
#define IDR_DEMO_ICON_WORKSPACE 103
#define IDR_DEMO_ICON_NOTES 104
#define IDR_DEMO_ICON_ARCHIVE 105
#define IDR_DEMO_ICON_MEDIA 106
#define IDR_DEMO_ICON_MAIL 107
#define IDR_DEMO_ICON_CALENDAR 108
#define IDR_DEMO_ICON_TOOLS 109
#define IDR_DEMO_ICON_IDEAS 110
#define IDR_DEMO_ICON_EXPLORE 111
#define IDR_DEMO_ICON_PHOTOS 112
#define IDR_DEMO_ICON_MUSIC 113
#define IDR_DEMO_ICON_CODE 114
#define IDR_DEMO_ICON_DATA 115
#define IDR_DEMO_ICON_DOCUMENTS 116
#define IDR_DEMO_ICON_PRESENTATIONS 117
#define IDR_DEMO_ICON_SPREADSHEETS 118
#define IDR_DEMO_ICON_COMMUNICATION 119
#define IDR_DEMO_ICON_VIDEO 120
#define IDR_DEMO_ICON_ENGINEERING 121
#define IDR_DEMO_ICON_AI 122
#define IDR_DEMO_ICON_GAMING 123
#define IDR_DEMO_ICON_OPERATIONS 124
#define IDR_DEMO_ICON_TERMINAL 125
#define IDR_DEMO_ICON_WEB 126
#define IDR_DEMO_ICON_CLOUD 127
