/**
 * @file resource.h
 * @brief 资源标识符定义
 * @details 定义应用程序图标、字体等资源的ID
 */
#pragma once

#define IDI_APPICON 1
#define IDI_APPICON_SMALL 2
#define IDR_FA_FONT 3
#define IDR_FLUENT_REGULAR_FONT 4

// Approved context-menu artwork (PNG, sourced from official Fluent SVG paths).
#define IDR_MENU_SORT_NATIVE_LIGHT 20
#define IDR_MENU_SORT_NATIVE_DARK 21
#define IDR_MENU_DISPLAY_NATIVE_LIGHT 22
#define IDR_MENU_DISPLAY_NATIVE_DARK 23
#define IDR_MENU_WIDGETS_NATIVE_LIGHT 24
#define IDR_MENU_WIDGETS_NATIVE_DARK 25
#define IDR_MENU_PIN_NATIVE_LIGHT 26
#define IDR_MENU_PIN_NATIVE_DARK 27
#define IDR_MENU_ADD_PAGE_NATIVE_LIGHT 28
#define IDR_MENU_ADD_PAGE_NATIVE_DARK 29
#define IDR_MENU_SETTINGS_NATIVE_LIGHT 30
#define IDR_MENU_SETTINGS_NATIVE_DARK 31
#define IDR_MENU_PASTE_NATIVE_LIGHT 32
#define IDR_MENU_PASTE_NATIVE_DARK 33
#define IDR_MENU_NEW_ITEM_NATIVE_LIGHT 34
#define IDR_MENU_NEW_ITEM_NATIVE_DARK 35
#define IDR_MENU_REFRESH_NATIVE_LIGHT 36
#define IDR_MENU_REFRESH_NATIVE_DARK 37
#define IDR_MENU_COLLECTION 38
#define IDR_MENU_COLLECTION_GROUP 39
#define IDR_MENU_FILE_GROUP 40
#define IDR_MENU_DESKTOP_FILES 41
#define IDR_MENU_FOLDER_MAPPING 42
#define IDR_MENU_SEARCH 43
#define IDR_MENU_WORKSHOP 44
