/**
 * @file resource.h
 * @brief 资源标识符定义
 * @details 定义应用程序图标、字体等资源的ID
 */
#pragma once

#define IDI_APPICON 1
#define IDI_APPICON_SMALL 2
#define IDR_FA_FONT 3
#define IDR_FLUENT_REGULAR_FONT 4

// Fictional Fluent-style application icons used by Demo Mode.
// Keep this range contiguous; rendering indexes into it by visual identity.
#define IDR_DEMO_ICON_PROJECTS 100
#define IDR_DEMO_ICON_DESIGN 101
#define IDR_DEMO_ICON_FOCUS 102
#define IDR_DEMO_ICON_WORKSPACE 103
#define IDR_DEMO_ICON_NOTES 104
#define IDR_DEMO_ICON_ARCHIVE 105
#define IDR_DEMO_ICON_MEDIA 106
#define IDR_DEMO_ICON_MAIL 107
#define IDR_DEMO_ICON_CALENDAR 108
#define IDR_DEMO_ICON_TOOLS 109
#define IDR_DEMO_ICON_IDEAS 110
#define IDR_DEMO_ICON_EXPLORE 111
#define IDR_DEMO_ICON_PHOTOS 112
#define IDR_DEMO_ICON_MUSIC 113
#define IDR_DEMO_ICON_CODE 114
#define IDR_DEMO_ICON_DATA 115
#define IDR_DEMO_ICON_DOCUMENTS 116
#define IDR_DEMO_ICON_PRESENTATIONS 117
#define IDR_DEMO_ICON_SPREADSHEETS 118
#define IDR_DEMO_ICON_COMMUNICATION 119
#define IDR_DEMO_ICON_VIDEO 120
#define IDR_DEMO_ICON_ENGINEERING 121
#define IDR_DEMO_ICON_AI 122
#define IDR_DEMO_ICON_GAMING 123
#define IDR_DEMO_ICON_OPERATIONS 124
#define IDR_DEMO_ICON_TERMINAL 125
#define IDR_DEMO_ICON_WEB 126
#define IDR_DEMO_ICON_CLOUD 127
#define IDR_DEMO_ICON_FILES_LIBRARY 128
#define IDR_DEMO_ICON_FILES_BACKUP 129
#define IDR_DEMO_ICON_UTILITIES_MONITOR 130
#define IDR_DEMO_ICON_UTILITIES_SHIELD 131
#define IDR_DEMO_ICON_CREATIVE_PEN 132
#define IDR_DEMO_ICON_CREATIVE_MOTION 133
#define IDR_DEMO_ICON_DEVELOPMENT_IDE 134
#define IDR_DEMO_ICON_DEVELOPMENT_GIT 135
#define IDR_DEMO_ICON_OFFICE_PDF 136
#define IDR_DEMO_ICON_OFFICE_BOARD 137
#define IDR_DEMO_ICON_COMMUNICATION_MEETING 138
#define IDR_DEMO_ICON_COMMUNICATION_CONTACTS 139
#define IDR_DEMO_ICON_MEDIA_PLAYER 140
#define IDR_DEMO_ICON_MEDIA_PODCAST 141
#define IDR_DEMO_ICON_ENGINEERING_CAD 142
#define IDR_DEMO_ICON_ENGINEERING_CIRCUIT 143
#define IDR_DEMO_ICON_AI_ASSISTANT 144
#define IDR_DEMO_ICON_AI_AUTOMATION 145
#define IDR_DEMO_ICON_GAMING_ARCADE 146
#define IDR_DEMO_ICON_GAMING_RACING 147
#define IDR_DEMO_ICON_OPERATIONS_NETWORK 148
#define IDR_DEMO_ICON_OPERATIONS_LOGS 149
#define IDR_DEMO_ICON_WEB_BROWSER 150
#define IDR_DEMO_ICON_WEB_CLOUD 151
#define IDR_DEMO_ICON_FILES_DOWNLOAD 152
#define IDR_DEMO_ICON_UTILITIES_REMOTE 153
#define IDR_DEMO_ICON_CREATIVE_PALETTE 154
#define IDR_DEMO_ICON_DEVELOPMENT_DATABASE 155
#define IDR_DEMO_ICON_OFFICE_WRITER 156
#define IDR_DEMO_ICON_COMMUNICATION_MAIL 157
#define IDR_DEMO_ICON_MEDIA_PHOTO 158
#define IDR_DEMO_ICON_ENGINEERING_SIMULATION 159
#define IDR_DEMO_ICON_AI_PROMPT 160
#define IDR_DEMO_ICON_GAMING_QUEST 161
#define IDR_DEMO_ICON_OPERATIONS_CONTAINER 162
#define IDR_DEMO_ICON_WEB_DOWNLOAD 163
