#pragma once
#include "settings_search_index.h"
#include <functional>

namespace snowdesktop
{
struct StaticSearchDefinition
{
    SettingsPage page;
    const char* focusId;
    const char* labelKey;
    const char* descriptionKey;
};

constexpr StaticSearchDefinition kStaticSearchDefinitions[] = {
    {SettingsPage::QuickNavigation,"quickNav.view","quickNav.view","quickNav.description"},
    {SettingsPage::QuickNavigation,"quickNav.defaultEngine","quickNav.defaultEngine","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.layout.expandedWidth","quickNav.layout.expandedWidth","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.layout.collapsedWidth","quickNav.layout.collapsedWidth","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.layout.maximumHeight","quickNav.layout.maximumHeight","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.layout.visibleRows","quickNav.layout.visibleRows","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.layout.padding","quickNav.layout.padding","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.layout.searchHeight","quickNav.layout.searchHeight","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.layout.iconSize","quickNav.layout.iconSize","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.layout.gridGap","quickNav.layout.gridGap","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.layout.rowGap","quickNav.layout.rowGap","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.layout.fontSize","quickNav.layout.fontSize","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.layout.secondaryFontSize","quickNav.layout.secondaryFontSize","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.layout.searchFontSize","quickNav.layout.searchFontSize","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.layout.resultRowHeight","quickNav.layout.resultRowHeight","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.layout.labelLines","quickNav.layout.labelLines","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.layout.cornerRadius","quickNav.layout.cornerRadius","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.layout.tabRadius","quickNav.layout.tabRadius","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.layout.itemRadius","quickNav.layout.itemRadius","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.colors.search","quickNav.colors.search","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.colors.navigation","quickNav.colors.navigation","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.colors.results","quickNav.colors.results","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.searchBg","quickNav.color.searchBg","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.searchBorder","quickNav.color.searchBorder","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.searchText","quickNav.color.searchText","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.searchPlaceholder","quickNav.color.searchPlaceholder","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.searchFocus","quickNav.color.searchFocus","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.typeFill","quickNav.color.typeFill","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.typeText","quickNav.color.typeText","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.tabDefaultFill","quickNav.color.tabDefaultFill","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.tabDefaultStroke","quickNav.color.tabDefaultStroke","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.tabText","quickNav.color.tabText","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.tabHoverFill","quickNav.color.tabHoverFill","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.tabHoverStroke","quickNav.color.tabHoverStroke","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.tabActiveFill","quickNav.color.tabActiveFill","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.tabActiveStroke","quickNav.color.tabActiveStroke","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.tabActiveText","quickNav.color.tabActiveText","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.tabHoverText","quickNav.color.tabHoverText","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.iconPlateFill","quickNav.color.iconPlateFill","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.iconPlateBorder","quickNav.color.iconPlateBorder","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.headerText","quickNav.color.headerText","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.headerSeparator","quickNav.color.headerSeparator","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.resultFill","quickNav.color.resultFill","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.resultBorder","quickNav.color.resultBorder","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.appNameText","quickNav.color.appNameText","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.appTypeText","quickNav.color.appTypeText","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.appRowHoverFill","quickNav.color.appRowHoverFill","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.appRowHoverStroke","quickNav.color.appRowHoverStroke","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.selectedFill","quickNav.color.selectedFill","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.selectedBorder","quickNav.color.selectedBorder","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.selectedText","quickNav.color.selectedText","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.itemText","quickNav.color.itemText","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.itemHoverFill","quickNav.color.itemHoverFill","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.itemHoverStroke","quickNav.color.itemHoverStroke","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.scrollTrack","quickNav.color.scrollTrack","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.scrollThumbDefault","quickNav.color.scrollThumbDefault","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.scrollThumbHover","quickNav.color.scrollThumbHover","quickNav.description"},
    {SettingsPage::AppearanceTheme,"quickNav.color.emptyText","quickNav.color.emptyText","quickNav.description"},

    {SettingsPage::AppearanceTheme, "quickNav.layout", "quickNav.layout", "quickNav.description"},
    {SettingsPage::QuickNavigation, "quickNav.prefixes", "quickNav.prefixes", "quickNav.prefixes.hint"},
    {SettingsPage::QuickNavigation, "quickNav.engines", "quickNav.engines", "quickNav.engines.hint"},

    {SettingsPage::StatusBar, "statusBar.taskView", "statusBar.taskView", "statusBar.leftItems"},
    {SettingsPage::StatusBar, "statusBar.clockPanel", "statusBar.clockPanel", "statusBar.clickBehavior"},
    {SettingsPage::StatusBar, "statusBar.controlCenterPanel", "statusBar.controlCenterPanel", "statusBar.clickBehavior"},
    {SettingsPage::DesktopStyle, "desktopStyle.native", "settings.desktopStyle.native.title", "settings.desktopStyle.native.description"},
    {SettingsPage::DesktopStyle, "desktopStyle.taskbar-dock", "settings.desktopStyle.taskbar-dock.title", "settings.desktopStyle.taskbar-dock.description"},
    {SettingsPage::DesktopStyle, "desktopStyle.island", "settings.desktopStyle.island.title", "settings.desktopStyle.island.description"},
    {SettingsPage::DesktopStyle, "desktopStyle.merged", "settings.desktopStyle.merged.title", "settings.desktopStyle.merged.description"},
    {SettingsPage::DesktopStyle, "desktopStyle.side", "settings.desktopStyle.side.title", "settings.desktopStyle.side.description"},
    {SettingsPage::Dock, "dock.mergedBarHeight", "settings.bars.height", "settings.bars.height.description"},
    {SettingsPage::Dock, "dock.lastMonitorUseHomeSize", "settings.bars.homeSize", "settings.bars.homeSize.description"},
    {SettingsPage::StatusBar, "statusBar.mergedBarHeight", "settings.bars.height", "settings.bars.height.description"},
    {SettingsPage::Dock, "dock.reserveScreenSpace", "settings.dock.reserveScreenSpace", "settings.dock.reserveScreenSpace.description"},
    {SettingsPage::Taskbar, "taskbar.suppressSystemTaskbar", "settings.dock.suppressTaskbar", "settings.dock.suppressTaskbar.description"},
    {SettingsPage::AnimationPerformance, "animation.mode",
        "settings.animation.mode", "settings.animation.mode.description"},
    {SettingsPage::AnimationPerformance, "animation.popup",
        "settings.animation.popup", "settings.animation.popup.description"},
    {SettingsPage::AnimationPerformance, "animation.speed",
        "settings.animation.speed", "settings.animation.speed.description"},
    {SettingsPage::Dock, "animation.hover",
        "settings.animation.hover", "settings.animation.hover.description"},
    {SettingsPage::Dock, "animation.hoverScale",
        "settings.animation.hoverScale", "settings.animation.hoverScale.description"},
    {SettingsPage::Dock, "animation.launch",
        "settings.animation.launch", "settings.animation.launch.description"},
    {SettingsPage::Dock, "animation.window",
        "settings.animation.window", "settings.animation.window.description"},
    {SettingsPage::AnimationPerformance, "animation.frameLimit",
        "settings.animation.frameLimit", "settings.animation.frameLimit.description"},
    {SettingsPage::AnimationPerformance, "animation.energySaver",
        "settings.animation.energySaver", "settings.animation.energySaver.description"},
    {SettingsPage::AnimationPerformance, "animation.onBattery",
        "settings.animation.onBattery", "settings.animation.onBattery.description"},

    {SettingsPage::General, "start.explore", "start.title", "start.description"},
    {SettingsPage::General, "start.collection", "start.collection.title", "start.collection.description"},
    {SettingsPage::General, "start.move", "start.move.title", "start.move.description"},
    {SettingsPage::General, "start.collectionGroup", "start.collectionGroup.title", "start.collectionGroup.description"},
    {SettingsPage::General, "start.files", "start.files.title", "start.files.description"},
    {SettingsPage::StatusBar, "statusBar.enable", "statusBar.enabled", "settings.page.statusBar.description"},
    {SettingsPage::StatusBar, "statusBar.position", "statusBar.position", "settings.nav.statusBar"},
    {SettingsPage::StatusBar, "statusBar.monitor", "settings.dock.monitor", "settings.nav.statusBar"},
    {SettingsPage::StatusBar, "statusBar.scale", "statusBar.scale", "settings.nav.statusBar"},
    {SettingsPage::StatusBar, "statusBar.theme", "statusBar.defaultAppearance", "settings.nav.statusBar"},
    {SettingsPage::StatusBar, "statusBar.noWindow", "statusBar.noWindow", "settings.nav.statusBar"},
    {SettingsPage::StatusBar, "statusBar.maximizedWindow", "statusBar.maximizedWindow", "settings.nav.statusBar"},
    {SettingsPage::StatusBar, "statusBar.menu", "statusBar.menu", "statusBar.leftItems"},
    {SettingsPage::StatusBar, "statusBar.quickSearch", "statusBar.quickSearch", "statusBar.leftItems"},
    {SettingsPage::StatusBar, "statusBar.inputMethod", "statusBar.inputMethod", "statusBar.information"},
    {SettingsPage::StatusBar, "statusBar.cpu", "statusBar.cpu", "statusBar.information"},
    {SettingsPage::StatusBar, "statusBar.memory", "statusBar.memory", "statusBar.information"},
    {SettingsPage::StatusBar, "statusBar.gpu", "statusBar.gpu", "statusBar.information"},
    {SettingsPage::StatusBar, "statusBar.traffic", "statusBar.traffic", "statusBar.information"},
    {SettingsPage::General, "start.folderMapping", "start.folderMapping.title", "start.folderMapping.description"},
    {SettingsPage::General, "start.fileGroup", "start.fileGroup.title", "start.fileGroup.description"},
    {SettingsPage::General, "start.dockPin", "start.dockPin.title", "start.dockPin.description"},
    {SettingsPage::General, "start.dockMapping", "start.dockMapping.title", "start.dockMapping.description"},
    {SettingsPage::General, "start.dockCollection", "start.dockCollection.title", "start.dockCollection.description"},
    {SettingsPage::General, "start.dockFiles", "start.dockFiles.title", "start.dockFiles.description"},
    {SettingsPage::General, "start.luaWidget", "start.luaWidget.title", "start.luaWidget.description"},
    {SettingsPage::General, "general.autoStart",
        "settings.general.startup",
        "settings.general.startup.description"},
    {SettingsPage::General, "general.advancedFeatures",
        "settings.general.advancedFeatures",
        "settings.general.advancedFeatures.description"},
    {SettingsPage::Desktop, "desktop.softwareDesktop",
        "settings.general.softwareDesktop",
        "settings.general.softwareDesktop.description"},
    {SettingsPage::ContextMenu, "contextMenu.extensions", "settings.contextMenu.extensions", "settings.contextMenu.description"},
    {SettingsPage::ContextMenu, "contextMenu.extensions", "settings.contextMenu.objects", "settings.contextMenu.locations"},
    {SettingsPage::ContextMenu, "contextMenu.extensions", "settings.contextMenu.background", "settings.contextMenu.locations"},
    {SettingsPage::ContextMenu, "contextMenu.items", "settings.contextMenu.inspect", "settings.contextMenu.hint"},
    {SettingsPage::ContextMenu, "contextMenu.application", "settings.contextMenu.viewApplications", "settings.contextMenu.extensions"},
    {SettingsPage::ContextMenu, "contextMenu.extension", "settings.contextMenu.viewExtensions", "settings.contextMenu.extensions"},
    {SettingsPage::ContextMenu, "contextMenu.batch", "settings.contextMenu.groupToggle", "settings.contextMenu.groupHint"},
    {SettingsPage::Calendar, "calendar.secondary", "settings.calendar.showSecondary", "settings.calendar.pageDescription"},
    {SettingsPage::Calendar, "calendar.events", "settings.calendar.events", "settings.calendar.pageDescription"},
    {SettingsPage::General, "general.language",
        "settings.general.language",
        "settings.general.language.description"},
    {SettingsPage::Desktop, "desktop.doubleClickHide",
        "settings.general.doubleClickHide",
        "settings.general.doubleClickHide.description"},
    {SettingsPage::General, "general.quickNavigation",
        "settings.general.quickNavigation",
        "settings.general.quickNavigation.description"},
    {SettingsPage::General, "general.quickNavigation.hotkey",
        "app.settings.hotkey",
        "settings.general.quickNavigation.description"},
    {SettingsPage::DesktopPages, "general.pageNavigation",
        "settings.general.pageNavigation",
        "settings.general.pageNavigation.description"},
    {SettingsPage::DesktopPages, "general.pageNavigation.previous",
        "app.settings.page_navigation_previous",
        "settings.general.pageNavigation.description"},
    {SettingsPage::DesktopPages, "general.pageNavigation.next",
        "app.settings.page_navigation_next",
        "settings.general.pageNavigation.description"},
    {SettingsPage::DesktopPages, "pages.order",
        "settings.pages.manage",
        "settings.pages.manage.description"},
    {SettingsPage::DesktopPages, "pages.add",
        "app.menu.add_page",
        "settings.pages.manage.description"},
    {SettingsPage::DesktopPages, "pages.grid",
        "settings.pages.grid",
        "settings.pages.grid.description"},
    {SettingsPage::DesktopPages, "pages.name",
        "settings.pages.name", "settings.pages.nameHint"},
    {SettingsPage::DesktopPages, "pages.delete",
        "settings.pages.delete", "settings.pages.deleteUnavailable"},
    {SettingsPage::Desktop, "desktop.passthrough",
        "settings.general.desktopPassthrough",
        "settings.general.desktopPassthrough.description"},
    {SettingsPage::Desktop, "desktop.passthrough.hotkey",
        "app.settings.hotkey",
        "settings.general.desktopPassthrough.description"},
    {SettingsPage::Dock, "dock.floatingShortcutMode",
        "settings.general.floatingDock",
        "settings.general.floatingDock.description"},
    {SettingsPage::Dock, "dock.floatingShortcutMode.hotkey",
        "app.settings.hotkey",
        "settings.general.floatingDock.description"},
    {SettingsPage::Dock, "personalization.dockAppearance",
        "guide.setting.dockAppearance.title", "guide.setting.dockAppearance"},
    {SettingsPage::AppearanceWidgets, "personalization.luaWidgetRowHeight",
        "app.settings.lua_widget_row_height", "settings.personalization.widgets.description"},
    {SettingsPage::DesktopPages, "pages.rows", "settings.pages.rows", "settings.pages.grid.description"},
    {SettingsPage::AppearanceTheme, "personalization.theme",
        "settings.personalization.theme",
        "settings.personalization.theme.description"},
    {SettingsPage::AppearanceTheme, "personalization.backgroundColor",
        "settings.personalization.colors",
        "settings.personalization.colors.description"},
    {SettingsPage::AppearanceTheme,
        "personalization.quickNavigationTheme",
        "app.settings.quick_nav_theme",
        "settings.personalization.theme.description"},
    {SettingsPage::AppearanceTheme,
        "personalization.collectionPopupTheme",
        "app.settings.collection_popup_theme",
        "settings.personalization.theme.description"},
    {SettingsPage::AppearanceTheme, "personalization.borderColor",
        "app.settings.component_border",
        "settings.personalization.colors.description"},
    {SettingsPage::AppearanceTheme, "personalization.widgetAlpha",
        "app.settings.bg_opacity",
        "settings.personalization.colors.description"},
    {SettingsPage::AppearanceTheme, "personalization.borderAlpha",
        "app.settings.border_opacity",
        "settings.personalization.colors.description"},
    {SettingsPage::AppearanceTheme, "personalization.borderWidth",
        "app.settings.border_width",
        "settings.personalization.colors.description"},
    {SettingsPage::AppearanceTheme, "personalization.edgeHighlight",
        "app.settings.edge_highlight",
        "settings.personalization.colors.description"},
    {SettingsPage::AppearanceTheme, "personalization.edgeHighlightWidth",
        "app.settings.edge_highlight_width",
        "settings.personalization.colors.description"},
    {SettingsPage::AppearanceTheme,
        "personalization.edgeHighlightStrength",
        "app.settings.edge_highlight_strength",
        "settings.personalization.colors.description"},
    {SettingsPage::AppearanceTheme, "personalization.enableGradient",
        "app.settings.enable_gradient",
        "settings.personalization.colors.description"},
    {SettingsPage::AppearanceTheme,
        "personalization.gradientEndAlpha",
        "app.settings.gradient_end_alpha",
        "settings.personalization.colors.description"},
    {SettingsPage::AppearanceTheme, "personalization.glass",
        "settings.personalization.glass",
        "settings.personalization.glass.description"},
    {SettingsPage::AppearanceTheme, "personalization.acrylic",
        "settings.personalization.acrylic",
        "settings.personalization.acrylic.description"},
    {SettingsPage::AppearanceTheme, "personalization.blurRadius",
        "app.settings.blur_radius",
        "settings.personalization.glass.description"},
    {SettingsPage::AppearanceTheme, "personalization.contentTheme",
        "app.settings.text_color",
        "settings.personalization.theme.description"},
    {SettingsPage::ContextMenu, "personalization.contextMenu",
        "settings.personalization.contextMenu",
        "settings.personalization.contextMenu.description"},
    {SettingsPage::AppearanceWidgets, "personalization.cornerRadius",
        "settings.personalization.widgets",
        "settings.personalization.widgets.description"},
    {SettingsPage::AppearanceWidgets, "personalization.barHeight",
        "app.settings.bar_height",
        "settings.personalization.widgets.description"},
    {SettingsPage::AppearanceWidgets, "personalization.widgetTransformCursors",
        "app.settings.widget_transform_cursors",
        "app.settings.widget_transform_cursors_hint"},
    {SettingsPage::WidgetBehavior, "personalization.scrollableTitleBarOnTop",
        "app.settings.scrollable_title_bar_position",
        "app.settings.scrollable_title_bar_position_hint"},
    {SettingsPage::AppearanceWidgets, "desktop.categoryLayout",
        "app.settings.tab_height",
        "settings.personalization.widgets.description"},
    {SettingsPage::WidgetBehavior, "personalization.showGroupTabCounts",
        "app.settings.group_show_count", "app.settings.group_show_count_hint"},
    {SettingsPage::WidgetBehavior, "personalization.popupHoverOpen",
        "app.settings.popup_hover_open", "app.settings.popup_hover_open_hint"},
    {SettingsPage::WidgetBehavior, "personalization.popupHoverDelayMs",
        "app.settings.popup_hover_delay", "app.settings.popup_hover_open_hint"},
    {SettingsPage::DesktopCategories,
        "desktop.categoryCounts",
        "app.settings.category_show_count",
        "settings.desktop.categoryLayout.description"},
    {SettingsPage::AppearanceWidgets, "desktop.spacing",
        "settings.desktop.spacing", "settings.desktop.spacing.description"},
    {SettingsPage::AppearanceDesktopIcons, "desktop.iconSize",
        "settings.desktop.iconSize", "settings.desktop.iconSize.description"},
    {SettingsPage::AppearanceDesktopIcons, "desktop.itemFontSize",
        "settings.desktop.typography",
        "settings.desktop.typography.description"},
    {SettingsPage::AppearanceDesktopIcons, "desktop.listFontSize",
        "app.settings.list_font_size",
        "settings.desktop.typography.description"},
    {SettingsPage::AppearanceTheme, "personalization.font", "font.title", "font.hint"},
    {SettingsPage::AppearanceDesktopIcons, "desktop.titleLines", "titleLines.desktop", "titleLines.hint"},
    {SettingsPage::AppearanceDesktopIcons, "desktop.largeFolderTitleLines", "titleLines.largeFolder", "titleLines.hint"},
    {SettingsPage::AppearanceDesktopIcons, "desktop.scrollingTitleLines", "titleLines.scrolling", "titleLines.hint"},
    {SettingsPage::AppearanceDesktopIcons, "desktop.titleOverflow", "titleOverflow.title", "titleOverflow.hint"},
    {SettingsPage::AppearanceDesktopIcons, "desktop.fontWeight",
        "app.settings.title_font_weight",
        "settings.desktop.typography.description"},
    {SettingsPage::AppearanceDesktopIcons, "desktop.shortcutArrow",
        "settings.desktop.shortcutArrow",
        "settings.desktop.shortcutArrow.description"},
    {SettingsPage::AppearanceIconBeautification, "desktop.iconBeautify",
        "settings.desktop.iconBeautify",
        "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification,
        "desktop.iconBeautify.mode",
        "app.settings.beautify_mode",
        "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification,
        "desktop.iconBeautify.backgroundColor",
        "app.settings.default_bg",
        "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification, "desktop.iconBeautify.glass",
        "app.settings.glass_enabled", "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification, "desktop.iconBeautify.blurRadius",
        "app.settings.blur_radius", "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification, "desktop.iconBeautify.edgeReflection",
        "app.settings.edge_highlight", "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification, "desktop.iconBeautify.reflectionWidth",
        "app.settings.edge_highlight_width", "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification, "desktop.iconBeautify.reflectionStrength",
        "app.settings.edge_highlight_strength", "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification,
        "desktop.iconBeautify.backgroundOpacity",
        "app.settings.bg_opacity_val",
        "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification,
        "desktop.iconBeautify.gradient",
        "app.settings.enable_gradient_bg",
        "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification,
        "desktop.iconBeautify.gradientEndColor",
        "app.settings.gradient_end_color",
        "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification,
        "desktop.iconBeautify.gradientDirection",
        "app.settings.beautify_gradient_dir",
        "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification,
        "desktop.iconBeautify.shape",
        "app.settings.beautify_shape",
        "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification,
        "desktop.iconBeautify.contentScale",
        "app.settings.beautify_content_scale",
        "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification,
        "desktop.iconBeautify.highlightStrength",
        "app.settings.beautify_texture_highlight",
        "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification,
        "desktop.iconBeautify.highlightSize",
        "app.settings.beautify_texture_highlight_size",
        "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification,
        "desktop.iconBeautify.highlightAngle",
        "app.settings.beautify_texture_highlight_angle",
        "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification,
        "desktop.iconBeautify.shadeStrength",
        "app.settings.beautify_texture_shade",
        "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification,
        "desktop.iconBeautify.edgeHighlight",
        "app.settings.beautify_texture_edge",
        "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification, "desktop.iconBeautify.filter",
        "app.settings.beautify_filter",
        "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification,
        "desktop.iconBeautify.filterColor",
        "app.settings.beautify_filter_color",
        "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification,
        "desktop.iconBeautify.filterStrength",
        "app.settings.beautify_filter_strength",
        "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification,
        "desktop.iconBeautify.shadowStrength",
        "app.settings.beautify_shadow_strength",
        "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification,
        "desktop.iconBeautify.outline",
        "app.settings.beautify_outline",
        "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification,
        "desktop.iconBeautify.outlineWidth",
        "app.settings.beautify_outline_width",
        "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification,
        "desktop.iconBeautify.outlineOpacity",
        "app.settings.beautify_outline_opacity",
        "settings.desktop.iconBeautify.description"},
    {SettingsPage::AppearanceIconBeautification,
        "desktop.iconBeautify.outlineColor",
        "app.settings.beautify_outline_color",
        "settings.desktop.iconBeautify.description"},
    {SettingsPage::DesktopCategories, "desktop.categoryRules",
        "app.settings.category_rules",
        "settings.desktop.categories.description"},
    {SettingsPage::DesktopCategories, "desktop.categories",
        "settings.desktop.categories",
        "settings.desktop.categories.description"},
    {SettingsPage::DesktopCategories, "desktop.collectPrograms",
        "app.settings.collect_programs",
        "settings.desktop.categories.description"},
    {SettingsPage::DesktopCategories, "desktop.category.add",
        "app.settings.add_category",
        "settings.desktop.categories.description"},
    {SettingsPage::Dock, "dock.enable", "settings.dock.enable",
        "settings.dock.enable.description"},
    {SettingsPage::Dock, "dock.position",
        "settings.dock.position", "settings.dock.position.description"},
    {SettingsPage::Dock, "dock.layout", "settings.dock.layout",
        "settings.dock.layout.description"},
    {SettingsPage::Dock, "dock.monitor", "settings.dock.monitor",
        "settings.dock.monitor.description"},
    {SettingsPage::Dock, "dock.thickness",
        "settings.dock.thickness", "settings.dock.thickness.description"},
    {SettingsPage::Dock, "dock.allowDesktopContentOverlap",
        "settings.dock.allowDesktopContentOverlap",
        "settings.dock.allowDesktopContentOverlap.description"},
    {SettingsPage::Dock, "dock.showOnlyWhenSummoned",
        "settings.dock.showOnlyWhenSummoned",
        "settings.dock.showOnlyWhenSummoned.description"},
    {SettingsPage::Dock, "dock.showFrequentItems",
        "settings.dock.frequentItems",
        "settings.dock.frequentItems.description"},
    {SettingsPage::Dock, "dock.floatingEdgeSwipe",
        "app.dock.floating_edge_swipe",
        "settings.dock.items.description"},
    {SettingsPage::Dock, "dock.edgeRevealGesture",
        "settings.dock.edgeRevealGesture", "settings.dock.edgeRevealGesture.description"},
    {SettingsPage::Dock, "dock.showWindowPreviews",
        "settings.dock.windowPreviews", "settings.dock.windowPreviews.description"},
    {SettingsPage::Dock, "dock.floatingEdgeSwipeBlockFullscreen",
        "settings.dock.blockFullscreenSwipe",
        "settings.dock.blockFullscreenSwipe.description"},
    {SettingsPage::Taskbar, "taskbar.displayMode",
        "settings.dock.suppressTaskbar", "settings.dock.suppressTaskbar.description"},
    {SettingsPage::Dock, "dock.showWindowsButton",
        "app.dock.show_windows_button",
        "settings.dock.items.description"},
    {SettingsPage::Dock, "dock.frequentItemCount",
        "app.settings.show_count",
        "settings.dock.frequentItems.description"},
    {SettingsPage::Taskbar, "taskbar.systemSettings",
        "settings.taskbar.systemSettings",
        "settings.taskbar.systemSettings.description"},
    {SettingsPage::Taskbar, "taskbar.theme",
        "settings.taskbar.theme", "settings.taskbar.theme.description"},
    {SettingsPage::Taskbar, "taskbar.contentTheme",
        "app.settings.taskbar_foreground_color",
        "settings.taskbar.theme.description"},
    {SettingsPage::Taskbar, "taskbar.backgroundColor",
        "app.settings.bg_color", "settings.taskbar.theme.description"},
    {SettingsPage::Taskbar, "taskbar.borderColor",
        "app.settings.border_color", "settings.taskbar.theme.description"},
    {SettingsPage::Taskbar, "taskbar.backgroundOpacity",
        "app.settings.bg_opacity", "settings.taskbar.theme.description"},
    {SettingsPage::Taskbar, "taskbar.borderOpacity",
        "app.settings.border_opacity", "settings.taskbar.theme.description"},
    {SettingsPage::Taskbar, "taskbar.glass",
        "app.settings.glass_enabled", "settings.taskbar.theme.description"},
    {SettingsPage::Taskbar, "taskbar.blurRadius",
        "app.settings.blur_radius", "settings.taskbar.theme.description"},
    {SettingsPage::Taskbar, "taskbar.acrylic",
        "app.settings.acrylic_noise", "settings.taskbar.theme.description"},
    {SettingsPage::Taskbar, "taskbar.dynamic.shellUi",
        "app.settings.taskbar_dynamic_shell_ui",
        "settings.taskbar.scenarioOverrides.description"},
    {SettingsPage::Taskbar, "taskbar.dynamic.maximizedWindow",
        "app.settings.taskbar_dynamic_maximized_window",
        "settings.taskbar.scenarioOverrides.description"},
    {SettingsPage::Taskbar, "taskbar.dynamic.visibleWindow",
        "app.settings.taskbar_dynamic_visible_window",
        "settings.taskbar.scenarioOverrides.description"},
    {SettingsPage::Taskbar, "taskbar.systemTheme",
        "app.settings.system_panel",
        "settings.taskbar.restartExplorer.description"},
    {SettingsPage::Taskbar, "taskbar.restartExplorer",
        "settings.taskbar.restartExplorer",
        "settings.taskbar.restartExplorer.description"},
    {SettingsPage::Widgets, "widgets.installed",
        "settings.widgets.installed",
        "settings.widgets.installed.description"},
    {SettingsPage::Widgets, "widgets.search",
        "app.settings.widgets_search",
        "settings.widgets.installed.description"},
    {SettingsPage::Widgets, "widgets.install",
        "app.settings.widgets_install_package",
        "settings.widgets.sources.description"},
    {SettingsPage::Widgets, "widgets.workshop",
        "app.settings.widgets_open_steam_workshop",
        "settings.widgets.sources.description"},
    {SettingsPage::Widgets, "widgets.developer",
        "app.settings.widgets_self_develop",
        "settings.widgets.sources.description"},
    {SettingsPage::Widgets, "widgets.included",
        "app.settings.widgets_builtin",
        "settings.widgets.installed.description"},
    {SettingsPage::Widgets, "widgets.sources", "settings.widgets.sources",
        "settings.widgets.sources.description"},
    {SettingsPage::Widgets, "widgets.permissions",
        "settings.widgets.permissions",
        "settings.widgets.permissions.description"},
    {SettingsPage::BackupAndData, "backup.layout", "settings.backup.layout",
        "settings.backup.layout.description"},
    {SettingsPage::BackupAndData, "backup.full", "settings.backup.full",
        "settings.backup.full.description"},
    {SettingsPage::BackupAndData, "backup.directory",
        "settings.backup.directory",
        "settings.backup.directory.description"},
    {SettingsPage::BackupAndData, "backup.migration",
        "app.settings.migrate_all_data",
        "settings.backup.full.description"},
    {SettingsPage::BackupAndData, "backup.clearData",
        "settings.backup.clearData", "settings.backup.clearData.description"},
    {SettingsPage::About, "about.version", "settings.about.version",
        "settings.about.version.description"},
    {SettingsPage::About, "about.profile", "app.settings.personal_homepages",
        "app.settings.about_description"},
    {SettingsPage::About, "about.project", "settings.about.project",
        "settings.about.project.description"},
    {SettingsPage::About, "about.website", "settings.about.officialWebsite",
        "settings.about.project.description"},
    {SettingsPage::About, "about.community", "app.settings.community",
        "app.settings.join_qq"},
    {SettingsPage::About, "about.thirdparty", "settings.about.thirdparty",
        "settings.about.thirdparty.description"},
    {SettingsPage::DeveloperTools, "developer.overrides",
        "settings.developer.overrides",
        "settings.developer.overrides.description"},
    {SettingsPage::DeveloperTools, "developer.tools",
        "settings.developer.tools",
        "settings.developer.tools.description"},
    {SettingsPage::DeveloperTools, "developer.agentSkill",
        "app.settings.widgets_agent_skill",
        "app.settings.widgets_agent_skill_description"},
    {SettingsPage::DeveloperTools, "developer.workspace",
        "app.settings.widgets_authoring_workspace",
        "settings.developer.tools.description"},
    {SettingsPage::DeveloperTools, "developer.cli",
        "app.settings.widgets_component_cli",
        "settings.developer.tools.description"},
    {SettingsPage::DeveloperTools, "developer.publish",
        "app.settings.widgets_authoring_publish",
        "app.settings.widgets_authoring_publish_description"},
    {SettingsPage::DeveloperTools, "developer.reference",
        "app.settings.widgets_authoring_reference",
        "app.settings.widgets_authoring_reference_description"},
    {SettingsPage::DeveloperTools, "developer.runtime",
        "app.settings.widgets_runtime_diagnostics",
        "settings.developer.tools.description"},
    {SettingsPage::Debug, "debug.profile", "settings.debug.profile.enabled", "settings.debug.profile.description"},
    {SettingsPage::Debug, "debug.desktop", "settings.debug.profile.desktop", "settings.debug.profile.chooseHint"},
    {SettingsPage::Debug, "debug.clearProfile", "settings.debug.profile.clear", "settings.debug.profile.clearHint"},
    {SettingsPage::Debug, "debug.demo_mode", "app.settings.demo_mode",
        "app.settings.demo_mode_hint"},
    {SettingsPage::Debug, "debug.initialization", "settings.debug.initialization",
        "settings.debug.initialization.description"},
    {SettingsPage::Debug, "debug.animation",
        "app.settings.animation_diagnostics",
        "app.settings.animation_diagnostics_desc"},
    {SettingsPage::Debug, "debug.resetUnlock", "settings.debug.resetUnlock",
        "settings.debug.resetUnlock.description"},
    {SettingsPage::Debug, "debug.crash", "app.settings.crash_test",
        "app.settings.crash_test_desc"},
};
inline void PopulateSettingsSearchCatalog(SettingsSearchIndexInput& input,
    const std::function<std::wstring(std::string_view)>& L,
    bool advancedFeaturesVisible, bool supportsQuickSettings)
{
            const auto pageContext = [&L](SettingsPage page) {
                switch (page)
                {
                case SettingsPage::QuickNavigation:
                    return L("quickNav.title");
                case SettingsPage::General:
                    return L("app.settings.general");
                case SettingsPage::AnimationPerformance:
                    return L("settings.nav.animation");
                case SettingsPage::Personalization:
                    return L("app.settings.appearance");
                case SettingsPage::AppearanceTheme:
                    return L("settings.personalization.theme");
                case SettingsPage::AppearanceWidgets:
                    return L("settings.personalization.widgets");
                case SettingsPage::WidgetBehavior:
                    return L("settings.widgetBehavior.title");
                case SettingsPage::AppearanceDesktopIcons:
                    return L("app.settings.desktop_icons");
                case SettingsPage::AppearanceIconBeautification:
                    return L("app.settings.icon_beautify");
                case SettingsPage::Desktop:
                    return L("settings.nav.desktop");
                case SettingsPage::DesktopPages:
                    return L("settings.nav.pages");
                case SettingsPage::DesktopCategories:
                    return L("settings.nav.categories");
                case SettingsPage::Dock:
                case SettingsPage::DockAndTaskbar:
                    return L("settings.nav.dock");
                case SettingsPage::Taskbar:
                    return L("settings.nav.taskbar");
                case SettingsPage::StatusBar:
                    return L("settings.nav.statusBar");
                case SettingsPage::DesktopStyle:
                    return L("settings.desktopStyle.title");
                case SettingsPage::Widgets:
                    return L("app.settings.widgets");
                case SettingsPage::BackupAndData:
                    return L("app.settings.backup");
                case SettingsPage::About:
                    return L("app.settings.about");
                case SettingsPage::DeveloperTools:
                    return L("app.settings.widgets_developer_tools");
                case SettingsPage::Debug:
                    return L("app.settings.debug");
                default:
                    return std::wstring{};
                }
            };
            input.staticSettings.reserve(std::size(kStaticSearchDefinitions));
            for (const auto& definition : kStaticSearchDefinitions)
            {
                if (std::string_view(definition.focusId) == "statusBar.controlCenterPanel" &&
                    !supportsQuickSettings) continue;
                StaticSettingSearchDescriptor descriptor;
                descriptor.page = CanonicalizeSettingsRoute(SettingsRoute::ForPage(definition.page, definition.focusId)).page;
                descriptor.focusId = definition.focusId;
                descriptor.label = L(definition.labelKey);
                descriptor.description = L(definition.descriptionKey);
                descriptor.context = pageContext(descriptor.page);
                descriptor.visible =
                    definition.page != SettingsPage::DeveloperTools &&
                        definition.page != SettingsPage::Debug
                    ? true
                    : (definition.page == SettingsPage::DeveloperTools
                        ? input.developerToolsVisible
                        : input.debugVisible);
                if (descriptor.focusId == "general.advancedFeatures" && !advancedFeaturesVisible) descriptor.visible = false;
                if (!descriptor.label.empty())
                    input.staticSettings.push_back(std::move(descriptor));
            }
}
}
